### ISSUE TITLE
Issue with created database

### ISSUE THREAD

**Issue by doughtmw** [dpasut/Top-Radio-to-spotify#5]
Hey, thanks for putting out this code! I am having issues with the database parsing, specifically in the `load_data()` function. 

I followed all of the installation steps, and when running the main `playlist.py` script the database is created successfully, but then I get the following error:

`Traceback (most recent call last):
  File "playlist.py", line 269, in <module>
    song_data_top100_indie, song_data_2017_indie,
  File "playlist.py", line 179, in load_data
    md5(artist,song)
sqlite3.OperationalError: no such table: json_each`

I'm sure I'm doing something silly, but help would be appreciated!

**Comment by jghjgfgh** [comment]
I'm pretty sure the version of Sqlite your Python is linked against is too low and missing some of the newer JSON stuff. What's the output of:
```
python2 -c 'import sqlite3; print sqlite3.sqlite_version'
```

**Comment by doughtmw** [comment]
Sorry for the delay in replying. The output of the above is `3.20.1`.

**Comment by doughtmw** [comment]
I tried updating sqlite to `3.22.0` but I'm still getting the same error as above.
